FROM python:3.11-slim

WORKDIR /challenge

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY ../api/app/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ../api/app ./api/app
COPY ../shared/ ./shared/

COPY ../api/run.py ./api/run.py

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8080

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "api.run:app"]