name: Local Tests

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Write GCP credentials to file
      run: echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > ./shared/config/gcp_cred.json

    - name: Write GCP vars to file
      run: echo '${{ secrets.GCP_VARS }}' > ./shared/config/gcp_vars.json

    - name: Build Docker image
      run: docker build -f dockerfiles/Dockerfile.api -t tu-latam-challenge-api .

    - name: Clean up sensitive files
      run: rm -f ./shared/config/gcp_cred.json ./shared/config/gcp_vars.json

    - name: Run API container
      run: docker run --name tu-latam-challenge-api -d -p 8080:8080 -e FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }} tu-latam-challenge-api

    - name: Set environment variable for local URL
      run: echo "BASE_URL=http://localhost:8080" >> $GITHUB_ENV

    - name: Install dependencies
      run: pip install -r api/test/api_test/requirements.txt  
      
    - name: Run local tests
      run: pytest api/test/api_test/integration_test.py

    - name: Stop and remove API container
      run: |
        docker stop tu-latam-challenge-api
        docker rm tu-latam-challenge-api
