name: Local Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -f dockerfiles/Dockerfile.api -t tu-latam-challenge-api .

    - name: Run API container
      run: docker run -p 8080:8080 -e FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }} tu-latam-challenge-api

    - name: Set environment variable for local URL
      run: echo "BASE_URL=http://localhost:8080" >> $GITHUB_ENV

    - name: Run local tests
      run: pytest api/test/api_test/integration_test.py

    - name: Stop and remove API container
      run: |
        docker stop tu-latam-challenge-api
        docker rm tu-latam-challenge-api